version: "3.9"  # optional since v1.27.0
services:
  kafka:
    image: spotify/kafka
    container_name: hlp-kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 9092
